name: Test Master
 
on:
 pull_request:
   branches: [ master ]
 
 
jobs:
 build-test:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       node-version: [17.x]
   steps:
   - uses: actions/checkout@v2
   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v1
     with:
       node-version: ${{ matrix.node-version }}
   - run: npm install
   - name: Cypress run
     uses: cypress-io/github-action@v2
     with:
        build: npm run build
        start: npm run dev
        wait-on: 'http://localhost:3000'
